# Remap prefix to Ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set-option -g renumber-windows on

# Split panes with - and |
bind-key - split-window -v
bind-key | split-window -h
unbind '"'
unbind %

# Enable mouse support
set -g mouse on

# Vi keybindings
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-line

# Longer scrollback
set-option -g history-limit 5000

# 256 color support
set -g default-terminal "screen-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
## Keep the SSH_AUTH_SOCK available across restored/restarted sessions
set -g @plugin 'tmux-plugins/tmux-sensible'
## Theming
set -g @plugin 'dracula/tmux'
## Save session
set -g @plugin 'tmux-plugins/tmux-resurrect'
## Fast fuzzy finder for tmux sessions, windows, panes, command history, and more
set -g @plugin 'sainnhe/tmux-fzf'
## Sensible copy-mode integration with system clipboards
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_selection 'clipboard'
set -g @yank_selection_mouse 'clipboard'

# Dracula theme config
set -g @dracula-show-powerline true
set -g @dracula-cpu-usage true
set -g @dracula-gpu-usage true
set -g @dracula-ram-usage true
set -g @dracula-show-fahrenheit false

# Initialize TMUX plugin manager (keep this at the very end)
run '~/.tmux/plugins/tpm/tpm'
